version: "3"
services:
  web:
    image: atsushikoga/apache-php:2.4-7.2
    ports:
      - "80:80"
    privileged: true
    volumes:
      - "./:/var/www/html"
    container_name: "tdd-kent-beck-apache-php"
